services:
  dev:
    container_name: damastech-frontend-dev
    build:
      context: .
      target: development # Esta e a seleção do stage do Dockerfile
    volumes:
      - ./:/app
      # Isola a node_modules para usar a de dentro do contêiner, e não a do host
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  prod:
    container_name: damastech-frontend-prod
    build:
      context: .
      target: production
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=production
